version: "2.4"

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:${jenkins_version:-lts}
    network_mode: bridge
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    mem_limit: 4g
    cpus: 2
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: "5m"
    restart: always

volumes:
  jenkins_home:
