version: "2.2"
services: 
  blue-ocean:
    image: jenkinsci/blueocean
    ports: 
      - 8080:8080
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
volumes: 
  jenkins-data:
    driver: local