version: '3.4'

services:
  
  nat123:
    build: 
      context: build
    image: nat123:3.180623
    network_mode: host
    environment:
      - USERNAME=
      - PASSWORD=
    volumes:
      - nat123_data:/nat123/data
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 10m
    tty: true
    restart: always

volumes:

  nat123_data:
    driver: local