version: "2"
services:
  aws-cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: aws-cli:ubuntu-1804
    volumes:
      - my-aws-profile:/root/.aws
    network_mode: bridge
    tty: true
volumes:
  my-aws-profile:
    driver: local
