version: "2.4"

services:
  mysql:
    image: mysql:8
    container_name: zabbix-mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
    command:
      --character-set-server=utf8
      --collation-server=utf8_bin
      --default-authentication-plugin=mysql_native_password
    volumes: 
      - mysql-data:/var/lib/mysql
    networks: 
      - zabbix-net

  java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-${ZABBIX_STACK_VERSION:-5.4}-latest
    container_name: zabbix-java-gateway
    volumes: 
      - zbx-java-gw-lib:/usr/sbin/zabbix_java/ext_lib
    networks: 
      - zabbix-net
          
  server:
    image: zabbix/zabbix-server-mysql:alpine-${ZABBIX_STACK_VERSION:-5.4}-latest
    container_name: zabbix-server
    environment: 
      DB_SERVER_HOST: "mysql"
      DB_SERVER_PORT: 3306
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSAL_ROOT_PASSWORD: "root"
      ZBX_JAVAGATEWAY: "java-gateway"
    ports: 
      - 10051:10051
    volumes: 
      - zbx-export:/var/lib/zabbix/export
      - zbx-snmptraps:/var/lib/zabbix/snmptraps
    networks: 
      - zabbix-net
      
  web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-${ZABBIX_STACK_VERSION:-5.4}-latest
    environment: 
      ZBX_SERVER_HOST: "server"
      DB_SERVER_HOST: "mysql"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "root"
    ports: 
      - 8080:8080
    networks: 
      - zabbix-net
    
  agent:
    image: zabbix/zabbix-agent:alpine-${ZABBIX_STACK_VERSION:-5.4}-latest
    environment: 
      ZBX_SERVER_HOST: server
    networks: 
      - zabbix-net


volumes: 
  mysql-data:
    driver: local
  zbx-java-gw-lib:
    driver: local
  zbx-export:
    driver: local
  zbx-snmptraps:
    driver: local

networks:
  zabbix-net:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1