filebeat.prospectors:
- type: log
  enabled: true
  paths:
    # - /var/log/*.log
    - /var/lib/docker/containers/*/*.log

output.elasticsearch:
  hosts: ["elk:9200"]

# setup.kibana:
#   host: "elk:5601"


#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 3
  #index.codec: best_compression
  #_source.enabled: false
