version: "2.4"
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev:v3.3.4
    platform: linux
    network_mode: bridge
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    environment:
      # - SERVER_ADDR
      # - SERVER_ADDR_IPV6
      # - METHOD=aes-256-gcm
      - METHOD=aes-256-cfb
      - PASSWORD=9MLSpPmNt
      # - TIMEOUT=300
      # - DNS_ADDRS=8.8.8.8,8.8.4.4
    restart: always
