version: '2'

volumes: 
  app-data:
  db-data:

services: 

  app:
    image: nextcloud
    container_name: nextcloud
    ports: 
      - 8085:80
    volumes: 
      - app-data:/var/www/html
    restart: always

  db:
    container_name: mariadb
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    volumes: 
      - db-data:/var/lib/mysql
    restart: always
    