version: "2"
services: 
  influxdb:
    image: influxdb:1.8
    ports: 
      - 8086:8086
    networks: 
      - influxdb
    volumes: 
      - influxdb-data:/var/lib/influxdb

networks: 
  influxdb:

volumes: 
  influxdb-data:
    driver: local