version: '3.2'

services:

  agent:
    image: portainer/agent:1.1.2
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: '10m'
    deploy:
      mode: global
      # placement:
      #   constraints: [node.platform.os == linux]

  web:
    image: portainer/portainer:1.19.2
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host # host|ingress
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - web_data:/data
    networks:
      - agent_network
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: '10m'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24


volumes:
  web_data:
