version: "2.4"
volumes:
  app-data:
  db-data:
services:
  app:
    image: nextcloud:17.0.2-apache
    platform: linux
    ports:
      - 8080:80
    volumes:
      - app-data:/var/www/html
    restart: always
  db:
    image: mariadb/server:10.3
    platform: linux
    environment:
      - MARIADB_ROOT_PASSWORD=M21roxpvM1gu2SuJ
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
      - MARIADB_PASSWORD=wTc6gZzA
    volumes:
      - db-data:/var/lib/mysql
    restart: always
