version: "2.2"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.204.1
    network_mode: bridge
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    mem_limit: 2g
    cpus: 2
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: "5m"
    restart: always
volumes:
  jenkins_data:
