version: "2.4"
services: 
  tomcat:
    image: tomcat:9.0.27
    volumes: 
      - ./tomcat/server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/web.xml:/usr/local/tomcat/conf/web.xml
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./tomcat/manager/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./tomcat/host-manager/context.xml:/usr/local/tomcat/webapps/host-manager/META-INF/context.xml
    ports: 
      - 8080:8080
    network_mode: bridge
    mem_limit: 1g
  nginx:
    image: nginx:1.17.5
    ports: 
      - 8081:80
    network_mode: bridge
    mem_limit: 1g
  apache:
    image: httpd:2.4.41
    ports: 
      - 8082:80
    network_mode: bridge
    mem_limit: 1g