version: "2.4"
services: 
  tomcat:
    image: tomcat:9.0.27
    ports: 
      - 8080:8080
    network_mode: bridge
    mem_limit: 1g
  nginx:
    image: nginx:1.17.5
    ports: 
      - 8081:80
    network_mode: bridge
    mem_limit: 1g
  apache:
    image: httpd:2.4.41
    ports: 
      - 8082:80
    network_mode: bridge
    mem_limit: 1g