version: "2.4"
services:
  db:
    container_name: mysql-server
    image: mysql:${MYSQL_VERSION:-5.7}
    # https://hub.docker.com/_/mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-time-zone=+08:00
      - --explicit_defaults_for_timestamp
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      # timezone
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      # data volume
      - db-data:/var/lib/mysql
    # logging:
    #   driver: json-file
    #   options:
    #     max-file: "1"
    #     max-size: 10m
    restart: always

  # WEB UI
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
