version: "2.4"
services:
  db:
    container_name: mysql-server
    image: mysql:${MYSQL_VERSION:-5.7}
    ports:
      - "3306:3306"
    command: --character-set-server=utf8 --collation-server=utf8_bin
    env_file:
      - ./mysql.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - db-data:/var/lib/mysql
    # logging:
    #   driver: json-file
    #   options:
    #     max-file: "1"
    #     max-size: 10m
    restart: always

  # WEB UI
  adminer:
    image: adminer
    restart: always
    ports:
      - 8306:8080

volumes:
  db-data:
