# chown 200 -R /sonatype-work
version: "2.4"
services:
  nexus:
    container_name: nexus
    image: sonatype/nexus
    network_mode: bridge
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/sonatype-work
    restart: always
volumes:
  nexus-data:
