version: '2'
services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    network_mode: bridge
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: '10m'

volumes:
  portainer_data: 
    driver: local
