version: "2.4"
services:
  db:
    container_name: mysql-server
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --character-set-server=utf8 --collation-server=utf8_bin
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m

  # WEB UI
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-config:
  db-data:
