# docker swarm mode

version: '3.4'
services:

  registry:
    image: registry:2.6.2
    ports:
      - "5000:5000"
    volumes:
      - /mnt/registry_data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml:ro
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 10m    
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager

networks:

  default:
    ipam:
      driver: default