version: '3'

services: 
  redis-server:
    container_name: redis-server
    image: redis
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass "reids password"
    
  redis-web:
    image: tenstartups/redis-commander
    container_name: redis-web
    restart: always
    ports:
      - 8081:8081
    command: --redis-host=redis-server --redis-port=6379
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes: 
  redis-data:
    driver: local